### ISSUE TITLE
Contact on Website Not Working

### ISSUE THREAD

**Issue by jbis9051** [magnito2/magnito2.github.io#1]
Hi!

I'd like to contact you to ask you a couple questions regarding how you made https://github.com/magnito2/media-backend. I am building a similar app and am a bit confused. I tried to access your website however the contact button doesn't seem to work. Is there any way for me to contact you?

**Comment by magnito2** [comment]
Hi Josh, I’ll update it. Anyway, I suggest you check out https://github.com/havfo/multiparty-meeting. I just switched to it after realizing it was 1 year ahead of what I was building. It will make a great start for you.

Sent from Mail for Windows 10

From: Josh Brown
Sent: Sunday, 12 April 2020 06:01
To: magnito2/magnito2.github.io
Cc: Subscribed
Subject: [magnito2/magnito2.github.io] Contact on Website Not Working (#1)

Hi!
I'd like to contact you to ask you a couple questions regarding how you made https://github.com/magnito2/media-backend. I am building a similar app and am a bit confused. I tried to access your website however the contact button doesn't seem to work. Is there any way for me to contact you?
